config/routes.rb
Rails.application.routes.draw do
  
  resources :state_cases
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    confirmations: 'members/confirmations'
  }

  get 'sectors', to: 'sectors#index'

  get 'home/index'

   root :to =>'home#index'

   resources :sectors

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/models/sector.rb
class Sector < ActiveRecord::Base
end

app/models/state_case.rb
class StateCase < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@welcome = 'Home'
  end
end

app/controllers/members/confirmations_controller.rb
class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/members/omniauth_callbacks_controller.rb
class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
before_filter :configure_sign_in_params, only: [:create]

skip_before_filter :verify_authenticity_token, :only => :destroy

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/members/unlocks_controller.rb
class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
	def index
		@sectors = Sector.all
	end
end

	def new
		@sectors = Sectors.new
	end

app/controllers/state_cases_controller.rb
class StateCasesController < ApplicationController
  before_action :set_state_case, only: [:show, :edit, :update, :destroy]

  # GET /state_cases
  # GET /state_cases.json
  def index
    @state_cases = StateCase.all
  end

  # GET /state_cases/1
  # GET /state_cases/1.json
  def show
  end

  # GET /state_cases/new
  def new
    @state_case = StateCase.new
  end

  # GET /state_cases/1/edit
  def edit
  end

  # POST /state_cases
  # POST /state_cases.json
  def create
    @state_case = StateCase.new(state_case_params)

    respond_to do |format|
      if @state_case.save
        format.html { redirect_to @state_case, notice: 'State case was successfully created.' }
        format.json { render :show, status: :created, location: @state_case }
      else
        format.html { render :new }
        format.json { render json: @state_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /state_cases/1
  # PATCH/PUT /state_cases/1.json
  def update
    respond_to do |format|
      if @state_case.update(state_case_params)
        format.html { redirect_to @state_case, notice: 'State case was successfully updated.' }
        format.json { render :show, status: :ok, location: @state_case }
      else
        format.html { render :edit }
        format.json { render json: @state_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /state_cases/1
  # DELETE /state_cases/1.json
  def destroy
    @state_case.destroy
    respond_to do |format|
      format.html { redirect_to state_cases_url, notice: 'State case was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state_case
      @state_case = StateCase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_case_params
      params.require(:state_case).permit(:state, :punctuation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/state_cases_helper.rb
module StateCasesHelper
end

app/views/home/index.html.slim
section.container
	h1 Home
	p = @welcome

	= link_to 'Sign out', destroy_member_session_url, class: 'btn btn-primary', method: :delete

app/views/layouts/application.html.slim
doctype html
html
	head
		title SAD
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
	body
		- if notice
			div.alert.alert-success
				p.notice = notice
		- if alert
			div.alert.alert-danger
				p.alert = alert
		== yield

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/sectors/index.html.slim
table
	thead
		th id
		th name
	tbody
		- @sectors.each do |s|
			tr
				td = s.id
				td = s.name

app/views/sectors/new.html.slim
h1 New sector

== render 'form'

= link_to 'Back', sectors_path

app/views/state_cases/_form.html.slim
= form_for @state_case do |f|
  - if @state_case.errors.any?
    #error_explanation
      h2 = "#{pluralize(@state_case.errors.count, "error")} prohibited this state_case from being saved:"
      ul
        - @state_case.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :punctuation
    = f.number_field :punctuation
  .actions = f.submit

app/views/state_cases/edit.html.slim
h1 Editing state_case

== render 'form'

= link_to 'Show', @state_case
'|
= link_to 'Back', state_cases_path

app/views/state_cases/index.html.slim
h1 Listing state_cases

table
  thead
    tr
      th State
      th Punctuation
      th
      th
      th

  tbody
    - @state_cases.each do |state_case|
      tr
        td = state_case.state
        td = state_case.punctuation
        td = link_to 'Show', state_case
        td = link_to 'Edit', edit_state_case_path(state_case)
        td = link_to 'Destroy', state_case, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New State case', new_state_case_path

app/views/state_cases/new.html.slim
h1 New state_case

== render 'form'

= link_to 'Back', state_cases_path

app/views/state_cases/show.html.slim
p#notice = notice

p
  strong State:
  = @state_case.state
p
  strong Punctuation:
  = @state_case.punctuation

= link_to 'Edit', edit_state_case_path(@state_case)
'|
= link_to 'Back', state_cases_path